# This is a basic workflow to help you get started with Actions

name: 'HFUT Auto daka'

# Controls when the workflow will run
on:
  watch:
    types: started
  push:
  schedule:
    - cron: '0 07 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v1
        - name: 'Set up Python'
          uses: actions/setup-python@v1
          with:
            python-version: '3.7'
        - name: 'Install requirements'
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: 'AutoClick'
          run: python submit.py
